travis:
  secure:
    BINSTAR_TOKEN: ijLmou48OL/I9Esj108zRMnzTTNTVLVY7kFIFg/Qnv8JfREFbMCjPq2z3l09QL+BgQK0r6Lo9wSGJBveX6nhjEsyAuSCgirexJpW/vJYW9e9bxOM7PrJZ8lGW3KNlu8y1dXwWScqIQ41gBkct5gRekP9a9nPeDNUjrsDAgBVWM+3QGKVXk1SpELTajsuTvb+7ot3nTh5gVjgGt7jbGEDcdkmQxvokwOHB+YPQs+FrUtaoFpAbgyvoYmVYm+Kdp1NRZ8Ys5iXgsTjzQGg73rvavncR1kocQ4wQmLbCciLAdBMKvIOGzASjA4N2fH1WSiJYpmqMOD1kzAZjRZ4mjFwdUP0cwUWvognZ3caX4uYCiW2KG+5oIZIxVDgrU/g3Blp4N6ruWo5LbXnEhPgKMpF1INclzenyoSplWaUuu00aBhMOySKPNEmemXsGSh43HDRt2N5G1pVS7Wn1EdE8pSdkzRJpM9zYi94l7ZRkxzk81+AtIkrLOWDnWVkqIONfaja+NLpwj8BKBo/T3t+jeyWoW05WZqbF6iB2PG/TZRYALJZ/bflGW3pzoJ2pzO3JtHhiNiEhqftBNiWev86NeC/ayzyEf/6jCErdg3P6sGXHJso3fDIKg6JJNWK1zNtX5jdrqGi9JFDm59Y5jPHPXBK7cnktgXEToehk4kYUlMnP0A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
